name: Continuous Integration

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Check out repository
        uses: actions/checkout@v5

      # https://github.com/actions/setup-go
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build and release application
        env:
          GH_TOKEN: ${{ github.token }}
        run: bash .github/scripts/continuous-integration.bash
